/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IExecutionsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>List&lt;ExecutionDetails&gt;</returns>
        List<ExecutionDetails> V1ExecutionsExecutionsInInstanceSessionClordidGet (string instance, string session, string clordid);

        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>ApiResponse of List&lt;ExecutionDetails&gt;</returns>
        ApiResponse<List<ExecutionDetails>> V1ExecutionsExecutionsInInstanceSessionClordidGetWithHttpInfo (string instance, string session, string clordid);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>Task of List&lt;ExecutionDetails&gt;</returns>
        System.Threading.Tasks.Task<List<ExecutionDetails>> V1ExecutionsExecutionsInInstanceSessionClordidGetAsync (string instance, string session, string clordid);

        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>Task of ApiResponse (List&lt;ExecutionDetails&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ExecutionDetails>>> V1ExecutionsExecutionsInInstanceSessionClordidGetAsyncWithHttpInfo (string instance, string session, string clordid);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ExecutionsApi : IExecutionsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExecutionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ExecutionsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExecutionsApi"/> class
        /// </summary>
        /// <returns></returns>
        public ExecutionsApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExecutionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ExecutionsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>List&lt;ExecutionDetails&gt;</returns>
        public List<ExecutionDetails> V1ExecutionsExecutionsInInstanceSessionClordidGet (string instance, string session, string clordid)
        {
             ApiResponse<List<ExecutionDetails>> localVarResponse = V1ExecutionsExecutionsInInstanceSessionClordidGetWithHttpInfo(instance, session, clordid);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>ApiResponse of List&lt;ExecutionDetails&gt;</returns>
        public ApiResponse< List<ExecutionDetails> > V1ExecutionsExecutionsInInstanceSessionClordidGetWithHttpInfo (string instance, string session, string clordid)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling ExecutionsApi->V1ExecutionsExecutionsInInstanceSessionClordidGet");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling ExecutionsApi->V1ExecutionsExecutionsInInstanceSessionClordidGet");
            // verify the required parameter 'clordid' is set
            if (clordid == null)
                throw new ApiException(400, "Missing required parameter 'clordid' when calling ExecutionsApi->V1ExecutionsExecutionsInInstanceSessionClordidGet");

            var localVarPath = "/v1/Executions/ExecutionsIn/{instance}/{session}/{clordid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (clordid != null) localVarPathParams.Add("clordid", this.Configuration.ApiClient.ParameterToString(clordid)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1ExecutionsExecutionsInInstanceSessionClordidGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ExecutionDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ExecutionDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ExecutionDetails>)));
        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>Task of List&lt;ExecutionDetails&gt;</returns>
        public async System.Threading.Tasks.Task<List<ExecutionDetails>> V1ExecutionsExecutionsInInstanceSessionClordidGetAsync (string instance, string session, string clordid)
        {
             ApiResponse<List<ExecutionDetails>> localVarResponse = await V1ExecutionsExecutionsInInstanceSessionClordidGetAsyncWithHttpInfo(instance, session, clordid);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="clordid">ClOrdId (tag 11) of the FIX Order</param>
        /// <returns>Task of ApiResponse (List&lt;ExecutionDetails&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ExecutionDetails>>> V1ExecutionsExecutionsInInstanceSessionClordidGetAsyncWithHttpInfo (string instance, string session, string clordid)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling ExecutionsApi->V1ExecutionsExecutionsInInstanceSessionClordidGet");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling ExecutionsApi->V1ExecutionsExecutionsInInstanceSessionClordidGet");
            // verify the required parameter 'clordid' is set
            if (clordid == null)
                throw new ApiException(400, "Missing required parameter 'clordid' when calling ExecutionsApi->V1ExecutionsExecutionsInInstanceSessionClordidGet");

            var localVarPath = "/v1/Executions/ExecutionsIn/{instance}/{session}/{clordid}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (clordid != null) localVarPathParams.Add("clordid", this.Configuration.ApiClient.ParameterToString(clordid)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1ExecutionsExecutionsInInstanceSessionClordidGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ExecutionDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ExecutionDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ExecutionDetails>)));
        }

    }
}
