/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface INewOrderSingleApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns></returns>
        void V1NewOrderSingleInstanceSessionClordidDelete (string instance, string session, string clordid = null);

        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> V1NewOrderSingleInstanceSessionClordidDeleteWithHttpInfo (string instance, string session, string clordid = null);
        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>List&lt;NewOrderSingleDetails&gt;</returns>
        List<NewOrderSingleDetails> V1NewOrderSingleOrdersOutInstanceGet (string instance);

        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>ApiResponse of List&lt;NewOrderSingleDetails&gt;</returns>
        ApiResponse<List<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceGetWithHttpInfo (string instance);
        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>List&lt;NewOrderSingleDetails&gt;</returns>
        List<NewOrderSingleDetails> V1NewOrderSingleOrdersOutInstanceSessionGet (string instance, string session, string orderstatus = null);

        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>ApiResponse of List&lt;NewOrderSingleDetails&gt;</returns>
        ApiResponse<List<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceSessionGetWithHttpInfo (string instance, string session, string orderstatus = null);
        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>NewOrderSingleDetails</returns>
        NewOrderSingleDetails V1NewOrderSingleOrdersOutInstanceSessionPost (string instance, string session, NewOrderSingle body = null);

        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of NewOrderSingleDetails</returns>
        ApiResponse<NewOrderSingleDetails> V1NewOrderSingleOrdersOutInstanceSessionPostWithHttpInfo (string instance, string session, NewOrderSingle body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task V1NewOrderSingleInstanceSessionClordidDeleteAsync (string instance, string session, string clordid = null);

        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> V1NewOrderSingleInstanceSessionClordidDeleteAsyncWithHttpInfo (string instance, string session, string clordid = null);
        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>Task of List&lt;NewOrderSingleDetails&gt;</returns>
        System.Threading.Tasks.Task<List<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceGetAsync (string instance);

        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>Task of ApiResponse (List&lt;NewOrderSingleDetails&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<NewOrderSingleDetails>>> V1NewOrderSingleOrdersOutInstanceGetAsyncWithHttpInfo (string instance);
        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>Task of List&lt;NewOrderSingleDetails&gt;</returns>
        System.Threading.Tasks.Task<List<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceSessionGetAsync (string instance, string session, string orderstatus = null);

        /// <summary>
        /// Get all Orders sent out for the target session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;NewOrderSingleDetails&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<NewOrderSingleDetails>>> V1NewOrderSingleOrdersOutInstanceSessionGetAsyncWithHttpInfo (string instance, string session, string orderstatus = null);
        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of NewOrderSingleDetails</returns>
        System.Threading.Tasks.Task<NewOrderSingleDetails> V1NewOrderSingleOrdersOutInstanceSessionPostAsync (string instance, string session, NewOrderSingle body = null);

        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (NewOrderSingleDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceSessionPostAsyncWithHttpInfo (string instance, string session, NewOrderSingle body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class NewOrderSingleApi : INewOrderSingleApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NewOrderSingleApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NewOrderSingleApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NewOrderSingleApi"/> class
        /// </summary>
        /// <returns></returns>
        public NewOrderSingleApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NewOrderSingleApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NewOrderSingleApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns></returns>
        public void V1NewOrderSingleInstanceSessionClordidDelete (string instance, string session, string clordid = null)
        {
             V1NewOrderSingleInstanceSessionClordidDeleteWithHttpInfo(instance, session, clordid);
        }

        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> V1NewOrderSingleInstanceSessionClordidDeleteWithHttpInfo (string instance, string session, string clordid = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleInstanceSessionClordidDelete");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling NewOrderSingleApi->V1NewOrderSingleInstanceSessionClordidDelete");

            var localVarPath = "/v1/NewOrderSingle/{instance}/{session}/clordid";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (clordid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "clordid", clordid)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleInstanceSessionClordidDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task V1NewOrderSingleInstanceSessionClordidDeleteAsync (string instance, string session, string clordid = null)
        {
             await V1NewOrderSingleInstanceSessionClordidDeleteAsyncWithHttpInfo(instance, session, clordid);

        }

        /// <summary>
        /// Delete a FIX Order.   Order can not be active for deletion.  (Must be in Cancelled, Rejected state.) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="clordid"> (optional)</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> V1NewOrderSingleInstanceSessionClordidDeleteAsyncWithHttpInfo (string instance, string session, string clordid = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleInstanceSessionClordidDelete");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling NewOrderSingleApi->V1NewOrderSingleInstanceSessionClordidDelete");

            var localVarPath = "/v1/NewOrderSingle/{instance}/{session}/clordid";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (clordid != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "clordid", clordid)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleInstanceSessionClordidDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>List&lt;NewOrderSingleDetails&gt;</returns>
        public List<NewOrderSingleDetails> V1NewOrderSingleOrdersOutInstanceGet (string instance)
        {
             ApiResponse<List<NewOrderSingleDetails>> localVarResponse = V1NewOrderSingleOrdersOutInstanceGetWithHttpInfo(instance);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>ApiResponse of List&lt;NewOrderSingleDetails&gt;</returns>
        public ApiResponse< List<NewOrderSingleDetails> > V1NewOrderSingleOrdersOutInstanceGetWithHttpInfo (string instance)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceGet");

            var localVarPath = "/v1/NewOrderSingle/OrdersOut/{instance}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleOrdersOutInstanceGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<NewOrderSingleDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<NewOrderSingleDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<NewOrderSingleDetails>)));
        }

        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>Task of List&lt;NewOrderSingleDetails&gt;</returns>
        public async System.Threading.Tasks.Task<List<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceGetAsync (string instance)
        {
             ApiResponse<List<NewOrderSingleDetails>> localVarResponse = await V1NewOrderSingleOrdersOutInstanceGetAsyncWithHttpInfo(instance);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all the orders sent out for this FIXServer instance across all FIX sessions. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <returns>Task of ApiResponse (List&lt;NewOrderSingleDetails&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<NewOrderSingleDetails>>> V1NewOrderSingleOrdersOutInstanceGetAsyncWithHttpInfo (string instance)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceGet");

            var localVarPath = "/v1/NewOrderSingle/OrdersOut/{instance}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleOrdersOutInstanceGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<NewOrderSingleDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<NewOrderSingleDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<NewOrderSingleDetails>)));
        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>List&lt;NewOrderSingleDetails&gt;</returns>
        public List<NewOrderSingleDetails> V1NewOrderSingleOrdersOutInstanceSessionGet (string instance, string session, string orderstatus = null)
        {
             ApiResponse<List<NewOrderSingleDetails>> localVarResponse = V1NewOrderSingleOrdersOutInstanceSessionGetWithHttpInfo(instance, session, orderstatus);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>ApiResponse of List&lt;NewOrderSingleDetails&gt;</returns>
        public ApiResponse< List<NewOrderSingleDetails> > V1NewOrderSingleOrdersOutInstanceSessionGetWithHttpInfo (string instance, string session, string orderstatus = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionGet");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionGet");

            var localVarPath = "/v1/NewOrderSingle/OrdersOut/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (orderstatus != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "orderstatus", orderstatus)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleOrdersOutInstanceSessionGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<NewOrderSingleDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<NewOrderSingleDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<NewOrderSingleDetails>)));
        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>Task of List&lt;NewOrderSingleDetails&gt;</returns>
        public async System.Threading.Tasks.Task<List<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceSessionGetAsync (string instance, string session, string orderstatus = null)
        {
             ApiResponse<List<NewOrderSingleDetails>> localVarResponse = await V1NewOrderSingleOrdersOutInstanceSessionGetAsyncWithHttpInfo(instance, session, orderstatus);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all Orders sent out for the target session 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXServer Instance</param>
        /// <param name="session">FIXServer target FIX session name</param>
        /// <param name="orderstatus">One or more FIX OrdStatus seperated by comma,  ex:  A,E (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;NewOrderSingleDetails&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<NewOrderSingleDetails>>> V1NewOrderSingleOrdersOutInstanceSessionGetAsyncWithHttpInfo (string instance, string session, string orderstatus = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionGet");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionGet");

            var localVarPath = "/v1/NewOrderSingle/OrdersOut/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (orderstatus != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "orderstatus", orderstatus)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleOrdersOutInstanceSessionGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<NewOrderSingleDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<NewOrderSingleDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<NewOrderSingleDetails>)));
        }

        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>NewOrderSingleDetails</returns>
        public NewOrderSingleDetails V1NewOrderSingleOrdersOutInstanceSessionPost (string instance, string session, NewOrderSingle body = null)
        {
             ApiResponse<NewOrderSingleDetails> localVarResponse = V1NewOrderSingleOrdersOutInstanceSessionPostWithHttpInfo(instance, session, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of NewOrderSingleDetails</returns>
        public ApiResponse< NewOrderSingleDetails > V1NewOrderSingleOrdersOutInstanceSessionPostWithHttpInfo (string instance, string session, NewOrderSingle body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionPost");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionPost");

            var localVarPath = "/v1/NewOrderSingle/OrdersOut/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleOrdersOutInstanceSessionPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NewOrderSingleDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (NewOrderSingleDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NewOrderSingleDetails)));
        }

        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of NewOrderSingleDetails</returns>
        public async System.Threading.Tasks.Task<NewOrderSingleDetails> V1NewOrderSingleOrdersOutInstanceSessionPostAsync (string instance, string session, NewOrderSingle body = null)
        {
             ApiResponse<NewOrderSingleDetails> localVarResponse = await V1NewOrderSingleOrdersOutInstanceSessionPostAsyncWithHttpInfo(instance, session, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Send a NewOrderSingle (MsgType &#x3D; D) to FIX endpoint. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (NewOrderSingleDetails)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<NewOrderSingleDetails>> V1NewOrderSingleOrdersOutInstanceSessionPostAsyncWithHttpInfo (string instance, string session, NewOrderSingle body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionPost");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling NewOrderSingleApi->V1NewOrderSingleOrdersOutInstanceSessionPost");

            var localVarPath = "/v1/NewOrderSingle/OrdersOut/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1NewOrderSingleOrdersOutInstanceSessionPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NewOrderSingleDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (NewOrderSingleDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NewOrderSingleDetails)));
        }

    }
}
