/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IOrderCancelReplaceRequestApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>NewOrderSingleDetails</returns>
        NewOrderSingleDetails V1OrderCancelReplaceRequestInstanceSessionPost (string instance, string session, OrderCancelReplaceRequest body = null);

        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of NewOrderSingleDetails</returns>
        ApiResponse<NewOrderSingleDetails> V1OrderCancelReplaceRequestInstanceSessionPostWithHttpInfo (string instance, string session, OrderCancelReplaceRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of NewOrderSingleDetails</returns>
        System.Threading.Tasks.Task<NewOrderSingleDetails> V1OrderCancelReplaceRequestInstanceSessionPostAsync (string instance, string session, OrderCancelReplaceRequest body = null);

        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (NewOrderSingleDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<NewOrderSingleDetails>> V1OrderCancelReplaceRequestInstanceSessionPostAsyncWithHttpInfo (string instance, string session, OrderCancelReplaceRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class OrderCancelReplaceRequestApi : IOrderCancelReplaceRequestApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCancelReplaceRequestApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OrderCancelReplaceRequestApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCancelReplaceRequestApi"/> class
        /// </summary>
        /// <returns></returns>
        public OrderCancelReplaceRequestApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCancelReplaceRequestApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OrderCancelReplaceRequestApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>NewOrderSingleDetails</returns>
        public NewOrderSingleDetails V1OrderCancelReplaceRequestInstanceSessionPost (string instance, string session, OrderCancelReplaceRequest body = null)
        {
             ApiResponse<NewOrderSingleDetails> localVarResponse = V1OrderCancelReplaceRequestInstanceSessionPostWithHttpInfo(instance, session, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of NewOrderSingleDetails</returns>
        public ApiResponse< NewOrderSingleDetails > V1OrderCancelReplaceRequestInstanceSessionPostWithHttpInfo (string instance, string session, OrderCancelReplaceRequest body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling OrderCancelReplaceRequestApi->V1OrderCancelReplaceRequestInstanceSessionPost");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling OrderCancelReplaceRequestApi->V1OrderCancelReplaceRequestInstanceSessionPost");

            var localVarPath = "/v1/OrderCancelReplaceRequest/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1OrderCancelReplaceRequestInstanceSessionPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NewOrderSingleDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (NewOrderSingleDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NewOrderSingleDetails)));
        }

        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of NewOrderSingleDetails</returns>
        public async System.Threading.Tasks.Task<NewOrderSingleDetails> V1OrderCancelReplaceRequestInstanceSessionPostAsync (string instance, string session, OrderCancelReplaceRequest body = null)
        {
             ApiResponse<NewOrderSingleDetails> localVarResponse = await V1OrderCancelReplaceRequestInstanceSessionPostAsyncWithHttpInfo(instance, session, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Send a Cancel/Replace Request on a New Order Single. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (NewOrderSingleDetails)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<NewOrderSingleDetails>> V1OrderCancelReplaceRequestInstanceSessionPostAsyncWithHttpInfo (string instance, string session, OrderCancelReplaceRequest body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling OrderCancelReplaceRequestApi->V1OrderCancelReplaceRequestInstanceSessionPost");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling OrderCancelReplaceRequestApi->V1OrderCancelReplaceRequestInstanceSessionPost");

            var localVarPath = "/v1/OrderCancelReplaceRequest/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1OrderCancelReplaceRequestInstanceSessionPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NewOrderSingleDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (NewOrderSingleDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NewOrderSingleDetails)));
        }

    }
}
