/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IWebhooksApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a list of the current Webhook Subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>List&lt;WebHookSubscriptionDetails&gt;</returns>
        List<WebHookSubscriptionDetails> V1WebhooksInstanceSessionGet (string instance, string session);

        /// <summary>
        /// Get a list of the current Webhook Subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>ApiResponse of List&lt;WebHookSubscriptionDetails&gt;</returns>
        ApiResponse<List<WebHookSubscriptionDetails>> V1WebhooksInstanceSessionGetWithHttpInfo (string instance, string session);
        /// <summary>
        /// Delete a webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns></returns>
        void V1WebhooksInstanceSessionIdDelete (string instance, string session, int? id);

        /// <summary>
        /// Delete a webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> V1WebhooksInstanceSessionIdDeleteWithHttpInfo (string instance, string session, int? id);
        /// <summary>
        /// Update a Webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>WebHookSubscriptionDetails</returns>
        WebHookSubscriptionDetails V1WebhooksInstanceSessionIdPatch (string instance, string session, int? id, WebHookSubscription body = null);

        /// <summary>
        /// Update a Webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of WebHookSubscriptionDetails</returns>
        ApiResponse<WebHookSubscriptionDetails> V1WebhooksInstanceSessionIdPatchWithHttpInfo (string instance, string session, int? id, WebHookSubscription body = null);
        /// <summary>
        /// Create a new Webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>WebHookSubscriptionDetails</returns>
        WebHookSubscriptionDetails V1WebhooksInstanceSessionPost (string instance, string session, WebHookSubscription body = null);

        /// <summary>
        /// Create a new Webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of WebHookSubscriptionDetails</returns>
        ApiResponse<WebHookSubscriptionDetails> V1WebhooksInstanceSessionPostWithHttpInfo (string instance, string session, WebHookSubscription body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get a list of the current Webhook Subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>Task of List&lt;WebHookSubscriptionDetails&gt;</returns>
        System.Threading.Tasks.Task<List<WebHookSubscriptionDetails>> V1WebhooksInstanceSessionGetAsync (string instance, string session);

        /// <summary>
        /// Get a list of the current Webhook Subscriptions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>Task of ApiResponse (List&lt;WebHookSubscriptionDetails&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<WebHookSubscriptionDetails>>> V1WebhooksInstanceSessionGetAsyncWithHttpInfo (string instance, string session);
        /// <summary>
        /// Delete a webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task V1WebhooksInstanceSessionIdDeleteAsync (string instance, string session, int? id);

        /// <summary>
        /// Delete a webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> V1WebhooksInstanceSessionIdDeleteAsyncWithHttpInfo (string instance, string session, int? id);
        /// <summary>
        /// Update a Webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of WebHookSubscriptionDetails</returns>
        System.Threading.Tasks.Task<WebHookSubscriptionDetails> V1WebhooksInstanceSessionIdPatchAsync (string instance, string session, int? id, WebHookSubscription body = null);

        /// <summary>
        /// Update a Webhook subscription
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (WebHookSubscriptionDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<WebHookSubscriptionDetails>> V1WebhooksInstanceSessionIdPatchAsyncWithHttpInfo (string instance, string session, int? id, WebHookSubscription body = null);
        /// <summary>
        /// Create a new Webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of WebHookSubscriptionDetails</returns>
        System.Threading.Tasks.Task<WebHookSubscriptionDetails> V1WebhooksInstanceSessionPostAsync (string instance, string session, WebHookSubscription body = null);

        /// <summary>
        /// Create a new Webhook subscription.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (WebHookSubscriptionDetails)</returns>
        System.Threading.Tasks.Task<ApiResponse<WebHookSubscriptionDetails>> V1WebhooksInstanceSessionPostAsyncWithHttpInfo (string instance, string session, WebHookSubscription body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class WebhooksApi : IWebhooksApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WebhooksApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// </summary>
        /// <returns></returns>
        public WebhooksApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WebhooksApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get a list of the current Webhook Subscriptions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>List&lt;WebHookSubscriptionDetails&gt;</returns>
        public List<WebHookSubscriptionDetails> V1WebhooksInstanceSessionGet (string instance, string session)
        {
             ApiResponse<List<WebHookSubscriptionDetails>> localVarResponse = V1WebhooksInstanceSessionGetWithHttpInfo(instance, session);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a list of the current Webhook Subscriptions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>ApiResponse of List&lt;WebHookSubscriptionDetails&gt;</returns>
        public ApiResponse< List<WebHookSubscriptionDetails> > V1WebhooksInstanceSessionGetWithHttpInfo (string instance, string session)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionGet");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionGet");

            var localVarPath = "/v1/Webhooks/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<WebHookSubscriptionDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<WebHookSubscriptionDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<WebHookSubscriptionDetails>)));
        }

        /// <summary>
        /// Get a list of the current Webhook Subscriptions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>Task of List&lt;WebHookSubscriptionDetails&gt;</returns>
        public async System.Threading.Tasks.Task<List<WebHookSubscriptionDetails>> V1WebhooksInstanceSessionGetAsync (string instance, string session)
        {
             ApiResponse<List<WebHookSubscriptionDetails>> localVarResponse = await V1WebhooksInstanceSessionGetAsyncWithHttpInfo(instance, session);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a list of the current Webhook Subscriptions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <returns>Task of ApiResponse (List&lt;WebHookSubscriptionDetails&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<WebHookSubscriptionDetails>>> V1WebhooksInstanceSessionGetAsyncWithHttpInfo (string instance, string session)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionGet");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionGet");

            var localVarPath = "/v1/Webhooks/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<WebHookSubscriptionDetails>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<WebHookSubscriptionDetails>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<WebHookSubscriptionDetails>)));
        }

        /// <summary>
        /// Delete a webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns></returns>
        public void V1WebhooksInstanceSessionIdDelete (string instance, string session, int? id)
        {
             V1WebhooksInstanceSessionIdDeleteWithHttpInfo(instance, session, id);
        }

        /// <summary>
        /// Delete a webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> V1WebhooksInstanceSessionIdDeleteWithHttpInfo (string instance, string session, int? id)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionIdDelete");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionIdDelete");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->V1WebhooksInstanceSessionIdDelete");

            var localVarPath = "/v1/Webhooks/{instance}/{session}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Delete a webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task V1WebhooksInstanceSessionIdDeleteAsync (string instance, string session, int? id)
        {
             await V1WebhooksInstanceSessionIdDeleteAsyncWithHttpInfo(instance, session, id);

        }

        /// <summary>
        /// Delete a webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance">FIXSIM Instance</param>
        /// <param name="session">FIXSIM target FIX session name</param>
        /// <param name="id"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> V1WebhooksInstanceSessionIdDeleteAsyncWithHttpInfo (string instance, string session, int? id)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionIdDelete");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionIdDelete");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->V1WebhooksInstanceSessionIdDelete");

            var localVarPath = "/v1/Webhooks/{instance}/{session}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                null);
        }

        /// <summary>
        /// Update a Webhook subscription 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>WebHookSubscriptionDetails</returns>
        public WebHookSubscriptionDetails V1WebhooksInstanceSessionIdPatch (string instance, string session, int? id, WebHookSubscription body = null)
        {
             ApiResponse<WebHookSubscriptionDetails> localVarResponse = V1WebhooksInstanceSessionIdPatchWithHttpInfo(instance, session, id, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update a Webhook subscription 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of WebHookSubscriptionDetails</returns>
        public ApiResponse< WebHookSubscriptionDetails > V1WebhooksInstanceSessionIdPatchWithHttpInfo (string instance, string session, int? id, WebHookSubscription body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionIdPatch");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionIdPatch");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->V1WebhooksInstanceSessionIdPatch");

            var localVarPath = "/v1/Webhooks/{instance}/{session}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WebHookSubscriptionDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WebHookSubscriptionDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WebHookSubscriptionDetails)));
        }

        /// <summary>
        /// Update a Webhook subscription 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of WebHookSubscriptionDetails</returns>
        public async System.Threading.Tasks.Task<WebHookSubscriptionDetails> V1WebhooksInstanceSessionIdPatchAsync (string instance, string session, int? id, WebHookSubscription body = null)
        {
             ApiResponse<WebHookSubscriptionDetails> localVarResponse = await V1WebhooksInstanceSessionIdPatchAsyncWithHttpInfo(instance, session, id, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update a Webhook subscription 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="id"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (WebHookSubscriptionDetails)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WebHookSubscriptionDetails>> V1WebhooksInstanceSessionIdPatchAsyncWithHttpInfo (string instance, string session, int? id, WebHookSubscription body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionIdPatch");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionIdPatch");
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling WebhooksApi->V1WebhooksInstanceSessionIdPatch");

            var localVarPath = "/v1/Webhooks/{instance}/{session}/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WebHookSubscriptionDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WebHookSubscriptionDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WebHookSubscriptionDetails)));
        }

        /// <summary>
        /// Create a new Webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>WebHookSubscriptionDetails</returns>
        public WebHookSubscriptionDetails V1WebhooksInstanceSessionPost (string instance, string session, WebHookSubscription body = null)
        {
             ApiResponse<WebHookSubscriptionDetails> localVarResponse = V1WebhooksInstanceSessionPostWithHttpInfo(instance, session, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new Webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of WebHookSubscriptionDetails</returns>
        public ApiResponse< WebHookSubscriptionDetails > V1WebhooksInstanceSessionPostWithHttpInfo (string instance, string session, WebHookSubscription body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionPost");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionPost");

            var localVarPath = "/v1/Webhooks/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WebHookSubscriptionDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WebHookSubscriptionDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WebHookSubscriptionDetails)));
        }

        /// <summary>
        /// Create a new Webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of WebHookSubscriptionDetails</returns>
        public async System.Threading.Tasks.Task<WebHookSubscriptionDetails> V1WebhooksInstanceSessionPostAsync (string instance, string session, WebHookSubscription body = null)
        {
             ApiResponse<WebHookSubscriptionDetails> localVarResponse = await V1WebhooksInstanceSessionPostAsyncWithHttpInfo(instance, session, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a new Webhook subscription. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="instance"></param>
        /// <param name="session"></param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (WebHookSubscriptionDetails)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WebHookSubscriptionDetails>> V1WebhooksInstanceSessionPostAsyncWithHttpInfo (string instance, string session, WebHookSubscription body = null)
        {
            // verify the required parameter 'instance' is set
            if (instance == null)
                throw new ApiException(400, "Missing required parameter 'instance' when calling WebhooksApi->V1WebhooksInstanceSessionPost");
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling WebhooksApi->V1WebhooksInstanceSessionPost");

            var localVarPath = "/v1/Webhooks/{instance}/{session}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (instance != null) localVarPathParams.Add("instance", this.Configuration.ApiClient.ParameterToString(instance)); // path parameter
            if (session != null) localVarPathParams.Add("session", this.Configuration.ApiClient.ParameterToString(session)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("V1WebhooksInstanceSessionPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WebHookSubscriptionDetails>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (WebHookSubscriptionDetails) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(WebHookSubscriptionDetails)));
        }

    }
}
