/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// RawMessage
    /// </summary>
    [DataContract]
        public partial class RawMessage :  IEquatable<RawMessage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RawMessage" /> class.
        /// </summary>
        /// <param name="fixMessage">fixMessage.</param>
        public RawMessage(string fixMessage = default(string))
        {
            this.FixMessage = fixMessage;
        }
        
        /// <summary>
        /// Gets or Sets FixMessage
        /// </summary>
        [DataMember(Name="fixMessage", EmitDefaultValue=false)]
        public string FixMessage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RawMessage {\n");
            sb.Append("  FixMessage: ").Append(FixMessage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RawMessage);
        }

        /// <summary>
        /// Returns true if RawMessage instances are equal
        /// </summary>
        /// <param name="input">Instance of RawMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RawMessage input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FixMessage == input.FixMessage ||
                    (this.FixMessage != null &&
                    this.FixMessage.Equals(input.FixMessage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FixMessage != null)
                    hashCode = hashCode * 59 + this.FixMessage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
