/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ExecutionDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExecutionDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ExecutionDetails
        //private ExecutionDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExecutionDetails
            //instance = new ExecutionDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExecutionDetails
        /// </summary>
        [Test]
        public void ExecutionDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExecutionDetails
            //Assert.IsInstanceOfType<ExecutionDetails> (instance, "variable 'instance' is a ExecutionDetails");
        }


        /// <summary>
        /// Test the property 'ExecutionReportId'
        /// </summary>
        [Test]
        public void ExecutionReportIdTest()
        {
            // TODO unit test for the property 'ExecutionReportId'
        }
        /// <summary>
        /// Test the property 'NewOrderSingleId'
        /// </summary>
        [Test]
        public void NewOrderSingleIdTest()
        {
            // TODO unit test for the property 'NewOrderSingleId'
        }
        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }
        /// <summary>
        /// Test the property 'SessionName'
        /// </summary>
        [Test]
        public void SessionNameTest()
        {
            // TODO unit test for the property 'SessionName'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'ClOrdId'
        /// </summary>
        [Test]
        public void ClOrdIdTest()
        {
            // TODO unit test for the property 'ClOrdId'
        }
        /// <summary>
        /// Test the property 'ExecId'
        /// </summary>
        [Test]
        public void ExecIdTest()
        {
            // TODO unit test for the property 'ExecId'
        }
        /// <summary>
        /// Test the property 'FixMessage'
        /// </summary>
        [Test]
        public void FixMessageTest()
        {
            // TODO unit test for the property 'FixMessage'
        }
        /// <summary>
        /// Test the property 'LastQty'
        /// </summary>
        [Test]
        public void LastQtyTest()
        {
            // TODO unit test for the property 'LastQty'
        }
        /// <summary>
        /// Test the property 'LastPx'
        /// </summary>
        [Test]
        public void LastPxTest()
        {
            // TODO unit test for the property 'LastPx'
        }
        /// <summary>
        /// Test the property 'CumQty'
        /// </summary>
        [Test]
        public void CumQtyTest()
        {
            // TODO unit test for the property 'CumQty'
        }
        /// <summary>
        /// Test the property 'AvgPx'
        /// </summary>
        [Test]
        public void AvgPxTest()
        {
            // TODO unit test for the property 'AvgPx'
        }
        /// <summary>
        /// Test the property 'QtyRemaining'
        /// </summary>
        [Test]
        public void QtyRemainingTest()
        {
            // TODO unit test for the property 'QtyRemaining'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

    }

}
