/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewOrderSingleDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewOrderSingleDetailsTests
    {
        // TODO uncomment below to declare an instance variable for NewOrderSingleDetails
        //private NewOrderSingleDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewOrderSingleDetails
            //instance = new NewOrderSingleDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewOrderSingleDetails
        /// </summary>
        [Test]
        public void NewOrderSingleDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewOrderSingleDetails
            //Assert.IsInstanceOfType<NewOrderSingleDetails> (instance, "variable 'instance' is a NewOrderSingleDetails");
        }


        /// <summary>
        /// Test the property 'NewOrderSingleId'
        /// </summary>
        [Test]
        public void NewOrderSingleIdTest()
        {
            // TODO unit test for the property 'NewOrderSingleId'
        }
        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }
        /// <summary>
        /// Test the property 'SessionName'
        /// </summary>
        [Test]
        public void SessionNameTest()
        {
            // TODO unit test for the property 'SessionName'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'ClOrdId'
        /// </summary>
        [Test]
        public void ClOrdIdTest()
        {
            // TODO unit test for the property 'ClOrdId'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'OrdType'
        /// </summary>
        [Test]
        public void OrdTypeTest()
        {
            // TODO unit test for the property 'OrdType'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Price2'
        /// </summary>
        [Test]
        public void Price2Test()
        {
            // TODO unit test for the property 'Price2'
        }
        /// <summary>
        /// Test the property 'FixMessage'
        /// </summary>
        [Test]
        public void FixMessageTest()
        {
            // TODO unit test for the property 'FixMessage'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Test]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }
        /// <summary>
        /// Test the property 'VmOrdStatus'
        /// </summary>
        [Test]
        public void VmOrdStatusTest()
        {
            // TODO unit test for the property 'VmOrdStatus'
        }
        /// <summary>
        /// Test the property 'VmQtyExecuted'
        /// </summary>
        [Test]
        public void VmQtyExecutedTest()
        {
            // TODO unit test for the property 'VmQtyExecuted'
        }
        /// <summary>
        /// Test the property 'VmAvgPx'
        /// </summary>
        [Test]
        public void VmAvgPxTest()
        {
            // TODO unit test for the property 'VmAvgPx'
        }
        /// <summary>
        /// Test the property 'VmLastUpdate'
        /// </summary>
        [Test]
        public void VmLastUpdateTest()
        {
            // TODO unit test for the property 'VmLastUpdate'
        }

    }

}
