/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderCancelReplaceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderCancelReplaceRequestTests
    {
        // TODO uncomment below to declare an instance variable for OrderCancelReplaceRequest
        //private OrderCancelReplaceRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderCancelReplaceRequest
            //instance = new OrderCancelReplaceRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderCancelReplaceRequest
        /// </summary>
        [Test]
        public void OrderCancelReplaceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderCancelReplaceRequest
            //Assert.IsInstanceOfType<OrderCancelReplaceRequest> (instance, "variable 'instance' is a OrderCancelReplaceRequest");
        }


        /// <summary>
        /// Test the property 'NewOrderSingleId'
        /// </summary>
        [Test]
        public void NewOrderSingleIdTest()
        {
            // TODO unit test for the property 'NewOrderSingleId'
        }
        /// <summary>
        /// Test the property 'ExternalOrderId'
        /// </summary>
        [Test]
        public void ExternalOrderIdTest()
        {
            // TODO unit test for the property 'ExternalOrderId'
        }
        /// <summary>
        /// Test the property 'NewOrderQty'
        /// </summary>
        [Test]
        public void NewOrderQtyTest()
        {
            // TODO unit test for the property 'NewOrderQty'
        }
        /// <summary>
        /// Test the property 'NewPrice'
        /// </summary>
        [Test]
        public void NewPriceTest()
        {
            // TODO unit test for the property 'NewPrice'
        }
        /// <summary>
        /// Test the property 'NewPrice2'
        /// </summary>
        [Test]
        public void NewPrice2Test()
        {
            // TODO unit test for the property 'NewPrice2'
        }
        /// <summary>
        /// Test the property 'NewOrdType'
        /// </summary>
        [Test]
        public void NewOrdTypeTest()
        {
            // TODO unit test for the property 'NewOrdType'
        }
        /// <summary>
        /// Test the property 'XtraTags'
        /// </summary>
        [Test]
        public void XtraTagsTest()
        {
            // TODO unit test for the property 'XtraTags'
        }

    }

}
