/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderCancelRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderCancelRequestTests
    {
        // TODO uncomment below to declare an instance variable for OrderCancelRequest
        //private OrderCancelRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderCancelRequest
            //instance = new OrderCancelRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderCancelRequest
        /// </summary>
        [Test]
        public void OrderCancelRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderCancelRequest
            //Assert.IsInstanceOfType<OrderCancelRequest> (instance, "variable 'instance' is a OrderCancelRequest");
        }


        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'NewOrderSingleId'
        /// </summary>
        [Test]
        public void NewOrderSingleIdTest()
        {
            // TODO unit test for the property 'NewOrderSingleId'
        }
        /// <summary>
        /// Test the property 'ClOrdId'
        /// </summary>
        [Test]
        public void ClOrdIdTest()
        {
            // TODO unit test for the property 'ClOrdId'
        }
        /// <summary>
        /// Test the property 'Tif'
        /// </summary>
        [Test]
        public void TifTest()
        {
            // TODO unit test for the property 'Tif'
        }
        /// <summary>
        /// Test the property 'OrdType'
        /// </summary>
        [Test]
        public void OrdTypeTest()
        {
            // TODO unit test for the property 'OrdType'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Price2'
        /// </summary>
        [Test]
        public void Price2Test()
        {
            // TODO unit test for the property 'Price2'
        }
        /// <summary>
        /// Test the property 'XtraTags'
        /// </summary>
        [Test]
        public void XtraTagsTest()
        {
            // TODO unit test for the property 'XtraTags'
        }

    }

}
