/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RawMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RawMessageTests
    {
        // TODO uncomment below to declare an instance variable for RawMessage
        //private RawMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RawMessage
            //instance = new RawMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RawMessage
        /// </summary>
        [Test]
        public void RawMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RawMessage
            //Assert.IsInstanceOfType<RawMessage> (instance, "variable 'instance' is a RawMessage");
        }


        /// <summary>
        /// Test the property 'FixMessage'
        /// </summary>
        [Test]
        public void FixMessageTest()
        {
            // TODO unit test for the property 'FixMessage'
        }

    }

}
