/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SessionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SessionInfoTests
    {
        // TODO uncomment below to declare an instance variable for SessionInfo
        //private SessionInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SessionInfo
            //instance = new SessionInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SessionInfo
        /// </summary>
        [Test]
        public void SessionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SessionInfo
            //Assert.IsInstanceOfType<SessionInfo> (instance, "variable 'instance' is a SessionInfo");
        }


        /// <summary>
        /// Test the property 'SessionName'
        /// </summary>
        [Test]
        public void SessionNameTest()
        {
            // TODO unit test for the property 'SessionName'
        }
        /// <summary>
        /// Test the property 'FixVersion'
        /// </summary>
        [Test]
        public void FixVersionTest()
        {
            // TODO unit test for the property 'FixVersion'
        }
        /// <summary>
        /// Test the property 'SenderCompId'
        /// </summary>
        [Test]
        public void SenderCompIdTest()
        {
            // TODO unit test for the property 'SenderCompId'
        }
        /// <summary>
        /// Test the property 'TargetCompId'
        /// </summary>
        [Test]
        public void TargetCompIdTest()
        {
            // TODO unit test for the property 'TargetCompId'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Test]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'IsLoggedOn'
        /// </summary>
        [Test]
        public void IsLoggedOnTest()
        {
            // TODO unit test for the property 'IsLoggedOn'
        }
        /// <summary>
        /// Test the property 'IsAcceptor'
        /// </summary>
        [Test]
        public void IsAcceptorTest()
        {
            // TODO unit test for the property 'IsAcceptor'
        }
        /// <summary>
        /// Test the property 'IsSessionTime'
        /// </summary>
        [Test]
        public void IsSessionTimeTest()
        {
            // TODO unit test for the property 'IsSessionTime'
        }
        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Test]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }
        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Test]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'TimeZone'
        /// </summary>
        [Test]
        public void TimeZoneTest()
        {
            // TODO unit test for the property 'TimeZone'
        }
        /// <summary>
        /// Test the property 'AppDataDictionary'
        /// </summary>
        [Test]
        public void AppDataDictionaryTest()
        {
            // TODO unit test for the property 'AppDataDictionary'
        }
        /// <summary>
        /// Test the property 'SendingSeqNum'
        /// </summary>
        [Test]
        public void SendingSeqNumTest()
        {
            // TODO unit test for the property 'SendingSeqNum'
        }
        /// <summary>
        /// Test the property 'RcvdSeqNum'
        /// </summary>
        [Test]
        public void RcvdSeqNumTest()
        {
            // TODO unit test for the property 'RcvdSeqNum'
        }

    }

}
