/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebHoookEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebHoookEventTests
    {
        // TODO uncomment below to declare an instance variable for WebHoookEvent
        //private WebHoookEvent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebHoookEvent
            //instance = new WebHoookEvent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebHoookEvent
        /// </summary>
        [Test]
        public void WebHoookEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebHoookEvent
            //Assert.IsInstanceOfType<WebHoookEvent> (instance, "variable 'instance' is a WebHoookEvent");
        }



    }

}
