/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebHookSubscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebHookSubscriptionTests
    {
        // TODO uncomment below to declare an instance variable for WebHookSubscription
        //private WebHookSubscription instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebHookSubscription
            //instance = new WebHookSubscription();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebHookSubscription
        /// </summary>
        [Test]
        public void WebHookSubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebHookSubscription
            //Assert.IsInstanceOfType<WebHookSubscription> (instance, "variable 'instance' is a WebHookSubscription");
        }


        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Test]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }
        /// <summary>
        /// Test the property 'SessionName'
        /// </summary>
        [Test]
        public void SessionNameTest()
        {
            // TODO unit test for the property 'SessionName'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'WebHoookEvent'
        /// </summary>
        [Test]
        public void WebHoookEventTest()
        {
            // TODO unit test for the property 'WebHoookEvent'
        }

    }

}
