/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderCancelReplaceRequestApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class OrderCancelReplaceRequestApiTests
    {
        private OrderCancelReplaceRequestApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new OrderCancelReplaceRequestApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderCancelReplaceRequestApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OrderCancelReplaceRequestApi
            //Assert.IsInstanceOfType(typeof(OrderCancelReplaceRequestApi), instance, "instance is a OrderCancelReplaceRequestApi");
        }

        /// <summary>
        /// Test V1OrderCancelReplaceRequestInstanceSessionPost
        /// </summary>
        [Test]
        public void V1OrderCancelReplaceRequestInstanceSessionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //string session = null;
            //OrderCancelReplaceRequest body = null;
            //var response = instance.V1OrderCancelReplaceRequestInstanceSessionPost(instance, session, body);
            //Assert.IsInstanceOf<NewOrderSingleDetails> (response, "response is NewOrderSingleDetails");
        }
    }

}
