/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RawMessageApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RawMessageApiTests
    {
        private RawMessageApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RawMessageApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RawMessageApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RawMessageApi
            //Assert.IsInstanceOfType(typeof(RawMessageApi), instance, "instance is a RawMessageApi");
        }

        /// <summary>
        /// Test V1RawMessageInstanceSessionPost
        /// </summary>
        [Test]
        public void V1RawMessageInstanceSessionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //string session = null;
            //RawMessage body = null;
            //instance.V1RawMessageInstanceSessionPost(instance, session, body);
            
        }
    }

}
