/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SessionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SessionsApiTests
    {
        private SessionsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SessionsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SessionsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SessionsApi
            //Assert.IsInstanceOfType(typeof(SessionsApi), instance, "instance is a SessionsApi");
        }

        /// <summary>
        /// Test V1SessionsInstanceGet
        /// </summary>
        [Test]
        public void V1SessionsInstanceGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //var response = instance.V1SessionsInstanceGet(instance);
            //Assert.IsInstanceOf<List<SessionInfo>> (response, "response is List<SessionInfo>");
        }
        /// <summary>
        /// Test V1SessionsInstancePatch
        /// </summary>
        [Test]
        public void V1SessionsInstancePatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //SessionInfo body = null;
            //instance.V1SessionsInstancePatch(instance, body);
            
        }
        /// <summary>
        /// Test V1SessionsInstanceSessionDelete
        /// </summary>
        [Test]
        public void V1SessionsInstanceSessionDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //string session = null;
            //instance.V1SessionsInstanceSessionDelete(instance, session);
            
        }
    }

}
