/* 
 * FIXServer - API
 *
 * Open API for FIXServer integrations.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebhooksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WebhooksApiTests
    {
        private WebhooksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WebhooksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebhooksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WebhooksApi
            //Assert.IsInstanceOfType(typeof(WebhooksApi), instance, "instance is a WebhooksApi");
        }

        /// <summary>
        /// Test V1WebhooksInstanceSessionGet
        /// </summary>
        [Test]
        public void V1WebhooksInstanceSessionGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //string session = null;
            //var response = instance.V1WebhooksInstanceSessionGet(instance, session);
            //Assert.IsInstanceOf<List<WebHookSubscriptionDetails>> (response, "response is List<WebHookSubscriptionDetails>");
        }
        /// <summary>
        /// Test V1WebhooksInstanceSessionIdDelete
        /// </summary>
        [Test]
        public void V1WebhooksInstanceSessionIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //string session = null;
            //int? id = null;
            //instance.V1WebhooksInstanceSessionIdDelete(instance, session, id);
            
        }
        /// <summary>
        /// Test V1WebhooksInstanceSessionIdPatch
        /// </summary>
        [Test]
        public void V1WebhooksInstanceSessionIdPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //string session = null;
            //int? id = null;
            //WebHookSubscription body = null;
            //var response = instance.V1WebhooksInstanceSessionIdPatch(instance, session, id, body);
            //Assert.IsInstanceOf<WebHookSubscriptionDetails> (response, "response is WebHookSubscriptionDetails");
        }
        /// <summary>
        /// Test V1WebhooksInstanceSessionPost
        /// </summary>
        [Test]
        public void V1WebhooksInstanceSessionPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string instance = null;
            //string session = null;
            //WebHookSubscription body = null;
            //var response = instance.V1WebhooksInstanceSessionPost(instance, session, body);
            //Assert.IsInstanceOf<WebHookSubscriptionDetails> (response, "response is WebHookSubscriptionDetails");
        }
    }

}
